openapi: 3.0.3
info:
  description: This is the TeacherID Broker API
  version: 1.0.0
  title: TeacherID Broker API
paths:
  /associate:
    post:
      summary: Associate data points regarding a user
      security: 
      - api_key: [api_key]
      description: >-
        Used by calling systems to share associations between user attributes
        and identifiers.  For example, connecting an email address to a TRN, or
        a NINO to a service's local identifier
      operationId: associate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Association'
        description: Association Object
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Association'
        '405':
          description: Invalid input
  /find:
    post:
      summary: Find associations across datasets given the input user details
      security: 
      - api_key: [api_key]
      description: >-
        Used to retrieve identifiers and user attributes related to the supplied
        user identifiers and user attributes.
      operationId: find
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Find'
        description: Find Object
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Association'
        '405':
          description: Invalid input
servers:
  - url: https://dfe-twd-ts-brokerapi/api
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    Association:
      type: object
      required:
        - userAttributes
        - sourceSystem
      properties:
        userAttributes:
          type: array
          items:
            $ref: '#/components/schemas/UserAttribute'
        sourceSystem:
          type: string
          description: The identifier of the system making the association
    UserAttribute:
      type: object
      required:
        - type
        - value
      properties:
        type:
          type: string
          example: email
        value:
          type: string
          description: The value of the identifier
          example: john.doe@digital.education.gov.uk
    Find:
      type: object
      required:
        - userAttributes
      properties:
        userAttributes:
          type: array
          items:
            $ref: '#/components/schemas/UserAttribute'
        matchType:
          type: string
          example: TRN,Email
          description: >-
            If specified, returns only user attributes found with the specified
            type.