version: 2
updates:

  - package-ecosystem: nuget
    directory: /dotnet-authserver
    schedule:
      interval: 'daily'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'daily'
