name: Deploy to Azure

inputs:
  environment_name:
    description: 'The name of the environment'
    required: true
  image_tag:
    description: 'github SHA of the image'
    required: true
  azure_credentials:
    description: 'JSON object containing a service principal that can read from Azure Key Vault'
    required: true
  terraform_vars:
    description: 'Path to the tfvars file for the environment'
    required: true
  terraform_backend_vars:
    description: 'Path to the backend tfvars file for the environment'
    required: true

outputs:
  environment_url:
    description: 'The base URL for the deployed environment'
    value: ${{ steps.terraform.outputs.url }}
  postgres_server_name:
    description: The name of the postgres server deployed
    value: ${{ steps.terraform.outputs.postgres_server_name }}


runs:
  using: composite

  steps:
    - name: Extract configuration from tfvars
      id: config
      run: |
        KEY_VAULT_NAME=$(jq -r '.key_vault_name' $TFVARS)
        RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name' $TFVARS)

        if [ -z "$KEY_VAULT_NAME" ]; then
          echo "::error ::Failed to extract key_vault_name from $TFVARS"
          exit 1
        fi

        if [ -z "$RESOURCE_GROUP_NAME" ]; then
          echo "::error ::Failed to extract resource_group_name from $TFVARS"
          exit 1
        fi

        echo ::set-output name=resource_group_name::$RESOURCE_GROUP_NAME
        echo ::set-output name=key_vault_name::$KEY_VAULT_NAME

      shell: bash
      env:
        TFVARS: ${{ inputs.terraform_vars }}
      working-directory: terraform

    - uses: Azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - uses: Azure/get-keyvault-secrets@v1
      id: get_secrets
      with:
        keyvault: ${{ steps.config.outputs.key_vault_name }}
        secrets: 'TFSTATE-CONTAINER-ACCESS-KEY'

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10
        terraform_wrapper: false

    - name: Terraform
      id: terraform
      run: |
        make ci ${{ inputs.environment_name }} terraform-apply
        cd terraform && echo ::set-output name=url::$(terraform output -raw auth_server_fqdn)/
        echo ::set-output name=postgres_server_name::$(terraform output -raw postgres_server_name)
      env:
        ARM_ACCESS_KEY: ${{ steps.get_secrets.outputs.TFSTATE-CONTAINER-ACCESS-KEY }}
        TF_VAR_azure_sp_credentials_json: ${{ inputs.azure_credentials }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      shell: bash
