version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Username=postgres;Password=teacher_identity;Database=teacher_identity
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:postgres

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=teacher_identity
      - POSTGRES_DB=teacher_identity

volumes:
  pg_data: