name: Build authorization server

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CONTAINER_REGISTRY: ghcr.io

defaults:
  run:
    working-directory: dotnet-authserver

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    outputs:
      docker_image: ${{ steps.image.outputs.tag }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: teacher_identity
          POSTGRES_PASSWORD: teacher_identity
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Lint
      run: |
        #https://github.com/dotnet/format/issues/1433
        dotnet tool install -g dotnet-format --version "6.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
        dotnet-format --verify-no-changes

    - name: Build
      run: dotnet build --configuration Release

    - name: Install Playwright
      run: pwsh ./test/TeacherIdentity.AuthServer.EndToEndTests/bin/Release/net6.0/playwright.ps1 install

    - name: Unit tests
      id: unit-tests
      run: dotnet test ./test/TeacherIdentity.AuthServer.Tests/ --configuration Release --no-build --logger trx
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Username=postgres;Password=teacher_identity;Database=teacher_identity"

    - name: Unit tests report
      uses: dorny/test-reporter@v1
      if: always() && (steps.unit-tests.outcome == 'success' || steps.unit-tests.outcome == 'failure')
      with:
        name: Unit test results
        path: 'dotnet-authserver/test/TeacherIdentity.AuthServer.Tests/**/*.trx'
        reporter: dotnet-trx

    - name: End-to-end tests
      id: e2e-tests
      run: dotnet test ./test/TeacherIdentity.AuthServer.EndToEndTests/ --configuration Release --no-build --logger trx
      env:
        AuthorizationServer__ConnectionStrings__DefaultConnection: "Host=localhost;Username=postgres;Password=teacher_identity;Database=teacher_identity"

    - name: End-to-end tests report
      uses: dorny/test-reporter@v1
      if: always() && (steps.e2e-tests.outcome == 'success' || steps.e2e-tests.outcome == 'failure')
      with:
        name: End-to-end test results
        path: 'dotnet-authserver/test/TeacherIdentity.AuthServer.EndToEndTests/**/*.trx'
        reporter: dotnet-trx
    
    - name: Generate migrations artifact
      run: |
        mkdir migrations
        migrations_file=migrations/script.sql

        dotnet tool install --global dotnet-ef
        dotnet ef migrations script --idempotent --output $migrations_file --configuration Release --project src/TeacherIdentity.AuthServer/TeacherIdentity.AuthServer.csproj --no-build

        # Remove the BOM
        sed -i $'1s/^\uFEFF//' $migrations_file

        # Ensure any errors return a non-zero exit code when migrations are applied
        echo "$(echo "\set ON_ERROR_STOP true"; echo ""; cat $migrations_file)" > $migrations_file

    - name: Publish migrations
      uses: actions/upload-artifact@v3
      with:
        name: migrations
        path: dotnet-authserver/migrations
        if-no-files-found: error

    - name: Publish
      run: |
        dotnet publish --configuration Release --no-build src/TeacherIdentity.AuthServer/TeacherIdentity.AuthServer.csproj
        dotnet publish --configuration Release --no-build src/TeacherIdentity.TestClient/TeacherIdentity.TestClient.csproj

    - name: Get Docker image tags
      id: image-tags
      run: |
        echo ::set-output name=authserver::$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):authserver-$GITHUB_SHA
        echo ::set-output name=testclient::$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):testclient-$GITHUB_SHA

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: AuthServer Docker build & push
      uses: docker/build-push-action@v2
      with:
        context: dotnet-authserver/src/TeacherIdentity.AuthServer
        push: true
        tags: ${{ steps.image-tags.outputs.authserver }}
        build-args: |
          GIT_SHA=${{ github.sha }}

    - name: TestClient Docker build & push
      uses: docker/build-push-action@v2
      with:
        context: dotnet-authserver/src/TeacherIdentity.TestClient
        push: true
        tags: ${{ steps.image-tags.outputs.testclient }}