name: Firewall rules Deletion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    name: List all Firewall Rules ( Preprod )
    runs-on: ubuntu-latest
    environment:
      name: preprod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Set environment variables (Preprod)
        shell: bash
        run: |
          tf_vars_file=terraform/workspace_variables/preprod.tfvars.json
          echo "KEY_VAULT_NAME=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV
          echo "RESOURCE_PREFIX=$(jq -r '.resource_prefix' ${tf_vars_file})" >> $GITHUB_ENV
          echo "ENV=$(jq -r '.environment_name' ${tf_vars_file})" >> $GITHUB_ENV
          echo "RESOURCE_GROUP_NAME=$(jq -r '.resource_group_name' ${tf_vars_file})" >> $GITHUB_ENV
  
      - name: List Firewall rules
        shell: bash
        run: |
        list-firewall-rules = "$(az postgres flexible-server firewall-rule list --name s165t01-getanid-preprod-psql --resource-group ${{ env.RESOURCE_GROUP_NAME }} | jq -r '[.0].name')"
   


     # - name: List firewall rule Preprod
      #  if: always()
       # uses: azure/CLI@v1
       # with:
       #   azcliversion: 2.30.0
       #   inlineScript: |
        #    az postgres flexible-server firewall-rule list --name s165t01-getanid-preprod-psql --resource-group ${{ env.RESOURCE_GROUP_NAME }}
         #   echo "if rule-name other than AllowAzure - Remove"
          #  az postgres flexible-server firewall-rule delete --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name s165t01-getanid-preprod-psql --end-ip-address 51.148.145.41 --yes
        #  az postgres flexible-server firewall-rule update --rule-name AllowAzure --name s165t01-getanid-preprod-psql  --resource-group ${{ env.RESOURCE_GROUP_NAME }} --remove property.list
        #    az postgres flexible-server firewall-rule policy intrusion-detection remove --AllowAzure

      
  